### ISSUE TITLE
Add SQL as target

### ISSUE THREAD

**Issue by kaans** [kaans/mqtli#116]
Add a new target to outputs that write a recevied message after all filters into an SQL database.

- [ ] Define the target database in the common section of the config file
  - set the connection string
  - optionally load an sql file which is loaded during start of the program (e.g. to initialize the database)
- [ ] For all messages, store the common attributes (topic, qos, retain). 
- Write the payload depending on the payload format:
  - [ ] Sparkplug:
    - message type
    - sparkplug version, group id, edge node id, device id, remaining metric level from topic
    - for each message type (birth, death, data, cmd, state) a property with an INSERT statement can be specified to write the data of the specific message into a table
  - [ ] all others
    - add an INSERT property to write the payload after all filters were applied

All Insert statements can contain template values (for topic, qos, retain, payload, or format specific values) that are replaced with the actual values.

Example: Output text to SQL table

```
database:
  sql:
    connection: sqlite::memory
    init_script: initialize_database.sql

topics:
  - topic: mqtli/topic
    outputs:
      - format:
          type: text
        target:
          type: sql
          insert_statement: INSERT INTO table (topic, qos, retain, payload) VALUES ({topic}, {qos}, {retain}, {payload})
```
